---
dependency:
  name: galaxy
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        snapd_confs:
          - snap: system
            key: proxy.http
            value: hogehoge
verifier:
  name: ansible

