---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: ubuntu-20.04
    image: megabytelabs/ubuntu-20.04:latest
    privileged: true
    pre_build_image: true
    command: /sbin/init
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        snapd_confs:
          - snap: system
            key: proxy.http
            value: hogehoge
verifier:
  name: ansible

