---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: ubuntu-20.04
    image: megabytelabs/ansible-molecule-ubuntu-20.04
    privileged: true
    pre_build_image: true
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
provisioner:
  name: ansible
  connection_options:
    ansible_connection: docker
    ansible_password: ${TEST_PASSWORD:-ansible}
    ansible_user: ${TEST_USER:-ansible}
  inventory:
    group_vars:
      all:
        ansible_become_password: ${TEST_BECOME_PASSWORD:-ansible}
        ansible_user: ${TEST_USER:-ansible}
        snapd_confs:
          - snap: system
            key: proxy.http
            value: hogehoge
verifier:
  name: ansible

