---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: ubuntu-20.04
    image: megabytelabs/ansible-molecule-ubuntu-20.04
    privileged: true
    pre_build_image: true
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        snapd_confs:
          - snap: system
            key: proxy.http
            value: hogehoge
verifier:
  name: ansible

