---
- name: Prepare
  hosts: all
  tasks:
    - name: Collect facts
      become: true
      ansible.builtin.setup:

    - debug: var=ansible_facts.distribution

    - name: Run apt update
      ansible.builtin.apt:
        update_cache: true
      when:
        - ansible_facts.distribution == "Ubuntu"

    - name: Install gpg
      ansible.builtin.apt:
        name: gpg
        update_cache: true
      when:
        - ansible_facts.distribution == "Debian"
